---
- name: Install Slurm Compute Daemon
  apt:
    name: slurmd
    state: present

- name: Deploy Cgroup configuration
  template:
    src: cgroup.conf.j2
    dest: /etc/slurm/cgroup.conf
    owner: slurm
    group: slurm
    mode: '0644'
  notify: Restart Slurmd

- name: Enable Cgroups v2 in GRUB
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash systemd.unified_cgroup_hierarchy=1"'
  notify: Update Grub